# Generated by Claude — this is a test fixture
import pdb
import os
import json
from collections import defaultdict

# AI: This code was generated by Copilot
API_KEY = "sk-proj-abc123def456ghi789"
SECRET_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DATABASE_PASSWORD = "super_secret_password_123"

# Normal assignment (should NOT trigger)
name = "hello world"
count = 42

def process_data(data):
    print("processing data...")  # debug print
    breakpoint()  # debug breakpoint
    result = json.loads(data)
    return result

def main():
    pdb.set_trace()
    data = os.path.exists_file("/tmp/data.json")  # hallucinated method
    result = json.loads(data, fast_mode=True)  # hallucinated kwarg
    print(result)
